### ISSUE TITLE
Update the base image buildroot config

### ISSUE THREAD

**Issue by luxas** [rancher/docker-from-scratch#19]
Hello, when I am building the docker-from-scratch on my machine, buildroot asks for many, many things. The file version is 2015.02 and buildroot 2015.05 is used, so it asks for those new options that have been added since that. 

It's not a serious error, it is fixed (I think) by ENTERing twenty times.

But anyway, it might be good with an updated buildroot config.

**Comment by ibuildthecloud** [comment]
I've seen this too, typically we run `make oldconfig` and check in the .config, but I think we didn't do that this time.

**Comment by datawolf** [comment]
@ibuildthecloud , it need us to type many, many Enter key for continue. so it is better to update the buildroot config.

**Comment by luxas** [comment]
Fixed on master. Now it's 2015.11
Thanks
